version: "3.9"

services:

  mongo:
    container_name: fastapi-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: on-failure
    networks:
      - custom

  web:
    container_name: fastapi-web
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    command: 'sh -c "gunicorn -c gunicorn.conf.py asgi:app"'
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - custom


networks:

  custom:
    driver: bridge
