services:

  mongo:
    container_name: fastapi-threads-mongo
    image: mongo:6.0.13
    restart: on-failure
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - custom

  web:
    container_name: fastapi-threads-web
    build: .
    restart: on-failure
    command: 'sh -c "gunicorn -c gunicorn.conf.py asgi:app"'
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    depends_on:
      - mongo
    networks:
      - custom


networks:

  custom:
    driver: bridge
